### ISSUE TITLE
Feature request: link to tags and notebooks

### ISSUE THREAD

**Issue by shinglyu** [ylc395/joplin-plugin-note-link-system#10]
There is another plugin that does this: https://discourse.joplinapp.org/t/go-to-tag-notebook-or-notes-via-links-and-by-highlighting-text-in-editor/12731

However it's usage is cumbersome and requires a few mouse clicks. If we can support tags and notebooks in quick link (`@@`) it would be very useful.

**Comment by ylc395** [comment]
How does this work? `@@# ` to get notes of a tag?

**Comment by shinglyu** [comment]
So I'd image it work like this. If I have a tag called `wip` and it has an ID `abcdefg12345`. 
1. I type `@@wip`
2. The dropdown will show a mixture of notes, tags, and notebooks which name matches `wip`. like this:
```
#wip    <-- this is a tag
wip-note  <-- this is a note's title
@wip-notebook <-- this is a notebook
```
3. If I select `#wip`, a link like this will be inserted:
```
[#wip](:/#abcdefg12345)
```
4. If I click on that link, the tag will be selected on the left-hand-side tags panel.

You can already insert links to tag manually using the syntax `[#tagname](:/#<tag ID>)`, but it's a lot of effort to get the tag's ID and type this manually. [This plugin] allows you to cover a selected text to this link but I don't like its design. It requires a lot of mouse clicks and selection. The `@@` quick link design is more elegant and won't break the typing flow.

**Comment by ylc395** [comment]
> You can already insert links to tag manually using the syntax [#tagname](:/#<tag ID>)

I think this is not Joplin feature but the plugin's feature. However, this feature is interesting, and is suitable to be a part of Note Link System. I'll add it.

**Comment by shinglyu** [comment]
Ah interesting! Maybe I uninstalled the plugin but forgot to restart Joplin so I thought the link still works. 

As always thank you for the prompt reply and bug fixes!

**Comment by ylc395** [comment]
Maybe it's better not to create plugin's custom syntax🤔
