### ISSUE TITLE
Improvement: reduce markdown view visual jitter

### ISSUE THREAD

**Issue by shinglyu** [ylc395/joplin-plugin-note-link-system#11]
Sorry me again. I'm not sure if this is technically possible but I'll report it anyway. 

If I enable *Markdown View: Auto Inserted Referrers List Position: Note Bottom*, whenever I type something in the markdown editor, the Backlinks section in the markdown view will briefly disappear, then appear. When it appears the markdown view's scroll position will move. See the screen recoding below:

https://user-images.githubusercontent.com/3250983/155689934-7cf40ca6-4181-44df-97be-b8867b7e2af9.mov

A few ideas for fixing it:
* Maybe we can try to fix the markdown view's scroll location, so even when the backlinks section is redenered it doesn't scroll the markdown view.
* Since I'm editing the current note, the backlinks are unlikely to change. Maybe we can cache the backlinks and render it quicker so the rendering delay it's less visible to the user?

Sorry for requesting so much in such a short time. I really enjoy the plugin and admire your hard work!

**Comment by ylc395** [comment]
It's difficult because Joplin just re-render HTML everytime we types in, even I do cache the backlinks. So re-inserting the list is inevitable.
