### ISSUE TITLE
Quick link menu should match theme

### ISSUE THREAD

**Issue by shbach** [ylc395/joplin-plugin-note-link-system#13]
Previously mentioned [here](https://discourse.joplinapp.org/t/plugin-note-link-system/21768/79?u=shbach) but creating this issue for tracking purposes.

When using a dark theme, the quick link menu should also be dark. Right now it is still white when using a dark theme which is jarring and doesn't match.

![image](https://user-images.githubusercontent.com/5298745/157568373-76a60321-e057-40c2-babd-e173392799bd.png)

**Comment by ylc395** [comment]
release as 0.5.4
