### ISSUE TITLE
Improve search in quick link

### ISSUE THREAD

**Issue by shbach** [ylc395/joplin-plugin-note-link-system#15]
It would be better if this plugin was able to use the same/similar search as built in to Joplin. Right now partial matches don't work, which makes the quick link not as efficient to use.

Joplin app:
![image](https://user-images.githubusercontent.com/5298745/158843578-16dd5138-d04a-4f96-a746-4351f4cfa9b8.png)

Note link system: 
![image](https://user-images.githubusercontent.com/5298745/158844319-f297e970-f7d8-4c8f-972d-b94061ddabb9.png)

**Comment by ylc395** [comment]
see #3

**Comment by shbach** [comment]
Thanks, using `$keyword*` worked. Is there a reason this isn't done by default?

**Comment by ylc395** [comment]
Yes, you're right. I usually use Chinese so didn't realize this problem.
