### ISSUE TITLE
能否让在导出“HTML-HTML目录”时候，将链接自动转化位  日记文件名.html的文件链接呢

### ISSUE THREAD

**Issue by pgy866** [ylc395/joplin-plugin-note-link-system#16]
能否让在导出“HTML-HTML目录”时候，将链接自动转化位  日记文件名.html的文件链接呢

**Comment by pgy866** [comment]
> 导出的问题不在我们的目标工作范围内

好吧。。是JOPLIN那边 处理吗？

**Comment by ylc395** [comment]
是的

**Comment by pgy866** [comment]
> 是的
好的 ，此问题 转移到 以下社区链接，谢谢您
https://github.com/laurent22/joplin/issues/6300#issuecomment-1073901480

**Comment by ylc395** [comment]
我知道你的意思了。这个问题在论坛里有人问了，见 https://discourse.joplinapp.org/t/links-to-other-notes-in-exported-html/5601

官方回答是还没实现

**Comment by pgy866** [comment]
> 我知道你的意思了。这个问题在论坛里有人问了，见 https://discourse.joplinapp.org/t/links-to-other-notes-in-exported-html/5601
> 
> 官方回答是还没实现

好的，谢谢您，20年，已经近2年啦，它没有被实现
也许他已经被抛弃啦。。。。。
