### ISSUE TITLE
@@ in the middle of a line will not enable create note.

### ISSUE THREAD

**Issue by bogdahn-fr** [ylc395/joplin-plugin-note-link-system#17]
Hello !
Thx for your fantastic job.

The @@ quick link does not work inside a string, if it's empty for the rest of the line it works. It's impossible to make new notes automaticly inside a existing note.
Here is an exemple of the normal behavior :

![image](https://user-images.githubusercontent.com/91743570/160237142-93b9487f-2ae0-4e44-972e-db71fc11a4fe.png)

And there is the bug :
![image](https://user-images.githubusercontent.com/91743570/160237257-ecc46787-d776-46b9-bb5b-845e329fd113.png)

As you can see, there is no choice to create a note or a to-do.

I think it was not here before.

General infos :

[Note Link System ](https://github.com/ylc395/joplin-plugin-note-link-system/issues/new#) v0.7.2

Joplin 2.7.15 (prod, win32)

Version de Synchro : 3
Version du profil : 41
Trousseau supporté : Oui

Révision : 8352e23

All others pluggings disabled.

**Comment by ylc395** [comment]
If you want to show 'create new note' or search with keyword, you should always type something after the popup's appearing. Otherwise the popup just list the most-recently-modified notes.
