### ISSUE TITLE
Doesn't link to "Section header" by itself

### ISSUE THREAD

**Issue by Galliver7** [ylc395/joplin-plugin-note-link-system#18]
Hi,  I can not link to Section header directory by note itself like below.

![スクリーンショット 2022-03-28 3 29 58のコピー](https://user-images.githubusercontent.com/8030470/160295499-8e01d7b2-56c4-464d-abe6-a97697990ba3.png)

I hope both link should work since it is pointing same resource.

Much appreciated for this product!

PS:
Maybe you'd mentioned this issue already on your forum post.
[Plugin: Note Link System - Plugins - Joplin Forum](https://discourse.joplinapp.org/t/plugin-note-link-system/21768#roadmap-9)
> Support Quick Link to current note
> Support finding self-reference

**Comment by ylc395** [comment]
[ylc395.noteLinkSystem.jpl.zip](https://github.com/ylc395/joplin-plugin-note-link-system/files/8362574/ylc395.noteLinkSystem.jpl.zip)

I don't publish new version so you can test with this.

**Comment by ylc395** [comment]
Update to v0.8.0
