### ISSUE TITLE
jump links in the same documents does not work

### ISSUE THREAD

**Issue by Fantasyfr** [ylc395/joplin-plugin-note-link-system#19]
First this plugin is amazing and thank you for your hard work.

I tried to add a jump link to a headline in the same document but it does not jump to this headline.
[dummy document#dummy](:/10e39fd3effc42d7b3395164ca723b19#dummy)

Can you confirm this issue?

Best regards
Frank

**Comment by ylc395** [comment]
Update to v0.8.0
