### ISSUE TITLE
Curly braces are unexpectedly hidden

### ISSUE THREAD

**Issue by lxianren** [ylc395/joplin-plugin-note-link-system#24]
Joplin: 2.8.8
Note Link System: v0.8.0

When curly braces are preceded by plain text and followed by a blank line, the curly braces and their contents will be hidden in the preview. I thought it was because of "markdown-it-attrs" in "Extra Markdown Syntax: Enable (need to restart Joplin)", but I still get the same result after turning off this option. Adding “\" before "{" and "}" doesn't work either.

**Comment by ylc395** [comment]
>  I thought it was because of "markdown-it-attrs" in "Extra Markdown Syntax: Enable (need to restart Joplin)"
You're right. 

> but I still get the same result after turning off this option
Restarting Joplin will make it work.

**Comment by lxianren** [comment]
> Restarting Joplin will make it work.

I've restarted joplin and it still doesn't work.

**Comment by ylc395** [comment]
Can you provide an example?

**Comment by lxianren** [comment]
![](https://s3.bmp.ovh/imgs/2022/06/24/780637bf63612b5b.gif)

**Comment by ylc395** [comment]
I see. markdown-it-attrs syntax always take effects when this plugin is enabled, so `aa{test4}` will be displayed as `aa` in markdown view. 

But if you set `Extra Markdown Syntax: Enable (need to restart Joplin)` as off, `aa{test4}` will be displayed as you expect in preview box.

**Comment by lxianren** [comment]
Actually, I have set `Extra Markdown Syntax: Enable (need to restart Joplin)` as off and restarted joplin. By the way, I have disabled all other plug-ins, and I found that only by disabling `note-link-system` can aa{test4} be displayed.

**Comment by ylc395** [comment]
Whether you set `Extra Markdown Syntax: Enable (need to restart Joplin)` as `off` or `on`,  `aa{test4}` won't be displayed  correctly in markdown view  because markdown-it-attrs syntax always take effects when this plugin is enabled. But that option works for link previewing box.

**Comment by lxianren** [comment]
Oh, I see. I got confused with the "viewer" and "link previewing box" you mentioned.
