### ISSUE TITLE
Why does it take up so much space when it's open?

### ISSUE THREAD

**Issue by ccvbc** [ylc395/joplin-plugin-note-link-system#25]
It can be seen that he takes up almost half of the space, this is not what I want to see, is there any setting needed to change his size, please let me know.
![image](https://user-images.githubusercontent.com/103726582/180713821-7131eec4-67f3-4e26-bc7f-3617caae1843.png)

**Comment by ylc395** [comment]
这个面板是可以拖动来改变尺寸的。Joplin 里所有面板都是能拖动的，和本插件的实现没有关系

**Comment by ccvbc** [comment]
I get that, I just want it to be the right size when it opens
