### ISSUE TITLE
Android related issues

### ISSUE THREAD

**Issue by ccvbc** [ylc395/joplin-plugin-note-link-system#26]
After trying it, I have mastered his usage on the pc and I have to say it is great. 
When I finished working on the computer, when I read it on the Android phone, I found that the jump function provided by the plug-in could not be realized.
may I ask if this is normal.

**Comment by ylc395** [comment]
Plugin system of Joplin is only enabled for its PC client. So any feature provided by this plugin won't work on android.

**Comment by ccvbc** [comment]
Well,I got it,thank you!
