### ISSUE TITLE
Conflict with "Sent snippet" plugin: Trigger code stops working

### ISSUE THREAD

**Issue by petzi53** [ylc395/joplin-plugin-note-link-system#27]
Thank you for this excellent plugin!! 

I noticed that there is a conflict with [Send snippet to different note](https://github.com/ambrt/joplin-plugin-send-snippet). Whenever "Send snippet" is installed and enabled, the trigger code for your plugin stops working. This is independent of the chosen code in the preferences of your plugin.

I am on macOS 12.5 (Monterey), Joplin Desktop Joplin 2.8.8 (prod, darwin), Note Link System  v0.8.0, and Send snippet to different note v1.0.0.

**Comment by ylc395** [comment]
what is the trigger code?

**Comment by petzi53** [comment]
I used `@@` but also tried it with `+++` and `€€`. All these trigger codes worked perfectly without the "Sent snippet" plugin. But after enabling "Sent snippet", your plugin stopped working the trigger functionality.

**Comment by ylc395** [comment]
I raise an issue in that plugin's repo. See https://github.com/ambrt/joplin-plugin-send-snippet/issues/1
