### ISSUE TITLE
Quick Link function a little wired~

### ISSUE THREAD

**Issue by LintaoAmons** [ylc395/joplin-plugin-note-link-system#3]
Thanks for making this wonderful plugin!!!

I think maybe there's a small issue about the `quick link` function. About the fuzzy finder.

## Scenario

I want to link a note which's title is `parameter expansion`.

- when I first type `@@pa`, it didn't find out the note, the pop-up window didn't show.

- when I continue to type until `@@para`, the popup shows one note which is not related to the `para`
     - ![image](https://user-images.githubusercontent.com/95092244/148720543-9203461a-24ea-4522-a859-8a23516645a2.png)

- I continue to type, until `@@paramete`, the popup hid again.
    - ![image](https://user-images.githubusercontent.com/95092244/148720698-5de807ab-f5ae-4700-8dc5-029b3f0b05c6.png)

- Finally, I finish the whole word `@@parameter`, the desired note shows up.
    - ![image](https://user-images.githubusercontent.com/95092244/148720661-b9649833-4079-4296-8b89-5bad82d8cb20.png)

**Comment by ylc395** [comment]
<img width="544" alt="图片" src="https://user-images.githubusercontent.com/12264626/148721496-8264a231-ae34-4b43-989a-df75f5103ad0.png">

You can set like this to enable prefix match

**Comment by LintaoAmons** [comment]
Thanks, perfect~~
