### ISSUE TITLE
Lag when cursor keeps moving on the TOC list.

### ISSUE THREAD

**Issue by Sinacs** [ylc395/joplin-plugin-note-link-system#30]
I'm using the Joplin built-in TOC feature. 

Recreate the problem:

1. Create the TOC.
2. Mouse cursor moving back and forth between multiple TOC links.

**Comment by ylc395** [comment]
what is heavy loading?

**Comment by Sinacs** [comment]
Just lag and hang.

**Comment by Sinacs** [comment]
https://user-images.githubusercontent.com/110529913/197744377-565a1b78-e36b-4f91-94a7-3068f6d16f2d.mov

**Comment by Sinacs** [comment]
But it won't happen when the note is without too much content:

https://user-images.githubusercontent.com/110529913/197749247-0cb472ab-1bfa-4861-8987-ba790a1c0ef5.mov
