### ISSUE TITLE
Quick Link feature sometimes doesn't let me create new note

### ISSUE THREAD

**Issue by akadaedalus** [ylc395/joplin-plugin-note-link-system#4]
I use Joplin to take daily notes.  The notes are named YYYY-MM-DD and it would help my workflow if I can create them in place within an index note I use to track the daily notes, named "YYYY-MM Overview".  The index is prepopulated with the strings YYYY-MM-01 through YYYY-MM-31, whether there is a matching note or not.

When I try to create tomorrow's note I start typing "@@2022-01-1" and it shows the "new Note"/"new Todo" options.   So far so good.  However I need to create it for the 11th so I finish it as "@@2022-01-11".  It then tries to link to my index note "2022-01 Overview" and does not allow me to create the new note.  It appears it's because the Overview page has the plain text "2022-01-11" within it.  I reproduced it with the Joplin search.  I can prevent this from happening with the search "title:2022-01-11".

I'm thinking that if the search doesn't provide an exact title match, you should always have the "new Note" and "new Todo" options.  So if I enter "2022-01-11" and it matches "2022-01 Overview" but is not an exact title match, I should be able to create note/todo.

P.S.: "2022-01-1" doesn't match any notes, it probably needs to be a full word within the note to match.

I'm running Joplin v.2.6.10.

**Comment by ylc395** [comment]
Since V0.4.0, you will always get *create new note* item when typing.
