### ISSUE TITLE
some suggestions 

### ISSUE THREAD

**Issue by justsome12** [ylc395/joplin-plugin-note-link-system#5]
Love it, thank you so much for this.
- It loads a little slow. And mostly I dont have backlinks anyway. so is it possible to only show the header, if there are backlinks to start with ( I am aware of manually adding)
- Is it possible that it is showed in both windows (MD and preivew)?

**Comment by ylc395** [comment]
1. maybe you can disable some features on setting panel of this plugin.
2. show what?
