### ISSUE TITLE
Bug: hover preview popup opens after I click a link

### ISSUE THREAD

**Issue by shinglyu** [ylc395/joplin-plugin-note-link-system#7]
When I'm in Note A and click on a link for Note B, I'll navigate to Note B, but the hover preview popup will still be shown in Note B.
1. I click on the link for Note B inside Note A
<img width="1113" alt="Screenshot 2022-02-23 at 11 18 11" src="https://user-images.githubusercontent.com/3250983/155300571-7e7d03f4-318c-41f0-8c6a-c6e08c02a068.png">
2. Note B opens up, but after a short delay a preview popup for Note B still shows up:
<img width="1113" alt="Screenshot 2022-02-23 at 11 18 23" src="https://user-images.githubusercontent.com/3250983/155300689-b24da4d4-2f66-4c7f-8223-045bc13de988.png">

Maybe we need to cancel any pending hover preview action when we navigate to another note?

I also tried to increase the setting `Previewer: Hover Delay Time(ms)`. But the preview popup will still show up, just slower.

**Comment by ylc395** [comment]
What's your Joplin Version? I can not reproduce this issue on my Joplin

**Comment by ylc395** [comment]
fixed in 0.5.2
